---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: "mariadb/server:latest"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_DATABASE
          value: metastore_db
        ports:
        - containerPort: 3306
        # resources:
        #   requests:
        #     memory: "500m"
        #     cpu: "500m"
        #   limits:
        #     memory: "4000m"
        #     cpu: "1000m"
        volumeMounts:
        - name: mariadb-for-hive
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-for-hive
        persistentVolumeClaim:
          claimName: maria-pv-claim
