apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.0.0
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    # config connect cluster
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1

    # schema registry [sc] config
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: "http://schema-registry:8081"
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: "http://schema-registry:8081"
  resources:
    requests:
        memory: 2Gi
        cpu: 500m
    limits:
        memory: 3Gi
        cpu: 1000m
  image: jpedroloureiro/kafka-connectors:latest
  # build:
  #   output:
  #     type: docker
  #     image: jpedroloureiro/kafka-connectors:latest
  #     pushSecret: docker-cfg
  #   plugins:
  #     - name: kafka-connect-avro-converter
  #       artifacts:
  #         - type: maven
  #           repository: https://mvnrepository.com
  #           group: io.confluent
  #           artifact: kafka-connect-avro-converter
  #           version: 7.0.1
  #     - name: debezium-postgres-connector
  #       artifacts:
  #         - type: tgz
  #           url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.3.1.Final/debezium-connector-postgres-1.3.1.Final-plugin.tar.gz
  #           sha512sum: 962a12151bdf9a5a30627eebac739955a4fd95a08d373b86bdcea2b4d0c27dd6e1edd5cb548045e115e33a9e69b1b2a352bee24df035a0447cb820077af00c03
