apiVersion: "argoproj.io/v1alpha1"
kind: Application
metadata:
  name: minio
  namespace: cicd
spec:
  project: big-data-on-k8s
  source:
    repoURL: https://github.com/JPedro-loureiro/big_data_k8s
    targetRevision: HEAD
    path: apps/datalake/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: datalake
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - "Validate=false"
      - "CreateNamespace=true"
      - "PrunePropagationPolicy=foreground"
      - "PruneLast=true"
    retry:
      limit: 3
      backoff:
        duration   : "5s"
        factor     : 2
        maxDuration: "1m"
